"""#356: one source dict in the shapes the PRODUCERS write (read_local_state
and the files it reads), covering every public key. Values are set only
where a producer sets them; used by test_d11_typed_projection.py."""
from __future__ import annotations

import copy
from typing import Any

_FULL: dict[str, Any] = {
    "portfolio": {
        "current": "proposer-quality",
        "nodes": {"proposer-quality": {"status": "active", "lever_metric": "loop.repeat_failure_rate",
                                       "direction": "down", "last_lever_value": 0.42}},
    },
    "scorecard": {
        "computed_at_utc": "2026-09-29T10:00:00Z",
        "window_days": 7,
        "gaps_status": "complete",
        "loop": {"integrations": 12, "confirmed_integration_ratio": 0.5, "repeat_failure_rate": 0.2,
                 "paused_supplier_outcomes": "unavailable", "execution_failure_events": 3},
        "cost": {"tokens_per_integration": 1200.5},
        "heldout": {"passed": 4, "checked": 4},
        "targets": {"integrations": 20, "repeat_failure_rate": 0.1},
        "reader_status": {"ledger": {"status": "complete"}, "completed": {"status": "present"},
                          "feeds": {"usage": {"status": "fresh", "age_seconds": 30, "max_age_seconds": 600}}},
        "feeds": {"feeds": {"usage": {"status": "fresh", "age_seconds": 30, "max_age_seconds": 600}}},
        "quality": {"artifact_graph": {"status": "complete", "counts": {"artifacts": 5, "components": 2, "leaves": 1},
                                       "oldest_leaves": [{"path": "nanobot/runtime/x.py"}], "unit_scan_status": "scanned"}},
        "control_plane": {"hypothesis_loop": {"total": 3, "supported": 1, "refuted": 1, "inconclusive": 1}},
        "gaps": [{"metric": "loop.repeat_failure_rate"}],
    },
    "evolution_tree": {
        "current_sha": "a" * 40,
        "nodes": {"a" * 40: {"ts": "2026-09-29T09:00:00Z", "cycle_id": "cycle-1", "parent_sha": None,
                             "branch": "selfevo/cycle-1", "fitness": {"reward": 0.9}}},
    },
    "hypotheses": {"entries": {"H-1": {"status": "supported", "verdict": "supported", "title": "Cache helps",
                                       "first_seen": "2026-09-20T00:00:00Z", "answered_at": "2026-09-21T00:00:00Z"}}},
    "hypotheses_durable": {"model": "wsjf", "selected_hypothesis_id": "HD-1", "entries": [
        {"hypothesis_id": "HD-1", "title": "Durable one", "selection_status": "selected", "wsjf": {"score": 3.5},
         "hadi": {"hypothesis": "If X then Y", "action": "Do X"}, "created_at": "2026-09-01T00:00:00Z"}]},
    "ledger_tail": [
        {"phase": "proposed", "cycle_id": "cycle-1", "ts": "2026-09-29T09:00:00Z", "task_title": "Improve cache",
         "demand_id": "gap:loop.repeat_failure_rate", "target_path": "nanobot/runtime/cache.py"},
        {"phase": "outcome", "cycle_id": "cycle-1", "ts": "2026-09-29T09:10:00Z", "outcome": "integrated",
         "sha": "a" * 40, "branch": "selfevo/cycle-1", "files_changed": ["nanobot/runtime/cache.py"],
         "reason": "success", "push_attempts": 1, "delivered": True},
    ],
    "ledger_history": [
        {"phase": "outcome", "cycle_id": "cycle-0", "ts": "2026-09-28T09:10:00Z", "outcome": "failed",
         "reason": "gate_failed", "_ledger_source": "archive:2026-09-28"},
    ],
    "demand_rotation": {"served": {"gap:loop.repeat_failure_rate": "2026-09-29T09:00:00Z"}},
    "demand_completed": {"entries": {"gap:cost.tokens": {"cycle_id": "cycle-0", "files_changed": ["a.py"]}}},
    "skill_reads": {"reads": [{"skill": "code-review", "confirmed": True}]},
    "skill_evals": [{"skill": "code-review", "delta": 0.1}],
    "ci_freshness": {"schema_version": 1, "observed_at_utc": "2026-09-29T10:00:00Z", "repositories": {
        "ozand/eeebot": {"actions_enabled": True, "freshness_state": "fresh", "latest_conclusion": "success",
                         "observed_at_utc": "2026-09-29T10:00:00Z",
                         "actions": {"state": "fresh", "enabled": True, "observed_at_utc": "2026-09-29T10:00:00Z"},
                         "freshness": {"state": "fresh", "latest_conclusion": "success",
                                       "latest_completed_at_utc": "2026-09-29T09:55:00Z", "age_seconds": 300}}}},
    "cycle_titles": {"cycle-1": "Improve cache", "a" * 40: "Improve cache"},
    "cycle_files": {"cycle-1": ["nanobot/runtime/cache.py"]},
    "llm_stats": {"cycle-1": {"calls": 2, "total_tokens": 900, "duration_ms": 1500.0, "last_finish_reason": "stop",
                              "any_length": False, "last_ts": "2026-09-29T09:05:00Z"}},
    "proposer_stats": {"calls": 3, "total_tokens": 1000, "duration_ms": 2000, "last_model": "qwen3.8-32b",
                       "last_ts": "2026-09-29T09:00:00Z",
                       "days": {"2026-09-29": {"calls": 3, "total_tokens": 1000, "duration_ms": 2000}}},
    "local_ci": {"probe": "present", "state": "ran", "exit_code": 0, "ok": True, "created_at_utc": "2026-09-29T08:00:00Z"},
    "executor_model_status": {"probe": "present", "latest_model": "qwen3.8-32b", "latest_class": "self_hosted",
                              "fallback_seen_recent": False, "checked_calls": 4},
    "executor_llm_stats": {"cycle_id": "cycle-1", "prompt_tokens": 5000, "ts": "2026-09-29T09:05:00Z",
                           "context_window": 32768},
    "compaction": {"status": "present", "rows": [{"cycle_id": "cycle-1", "reason": "compacted"}]},
    "token_heatmap": {
        "dates": ["2026-09-29"],
        "hourly": {"2026-09-29": [[10, 20, 0, 30, 2, "proposer"]] * 24},
        "five_min": {"2026-09-29": {"12": [10, 20, 0, 30, 2, "proposer"]}},
        "summary": {"total_tokens": 720, "total_calls": 48, "days_present": 1, "timezone": "UTC",
                    "quantiles_hourly": {"gateway": 20, "local": 10, "total": 30}},
    },
    "lessons": [{"id": "L-1", "title": "Retry is not a fix", "date": "2026-09-28", "cycle_id": "cycle-0",
                 "task_id": "", "hypothesis": "", "result": "", "insight": "private insight",
                 "problem": "private problem", "solution": "private solution", "source": "live"}],
    "subagent_records": [{"subagent_id": "sa-1", "cycle_id": "cycle-1", "goal_id": "g-1", "label": "explore",
                          "status": "done", "started_at": "2026-09-29T09:01:00Z", "finished_at": "2026-09-29T09:02:00Z",
                          "task_excerpt": "private task", "task_truncated": False, "task_bytes": 12,
                          "summary_excerpt": "private summary", "summary_truncated": False,
                          "result_excerpt": "private result", "result_truncated": False, "iteration_count": 3}],
    "derived_view": {
        "status": "present", "schema_version": 1, "generated_at_utc": "2026-09-29T09:00:00Z",
        "charter": {"source": "release_goals_md", "merged": False, "text": "Public charter text"},
        "derived_status": "present",
        "derived_priorities": [{"number": 3, "label": "Self label", "vector": "V1", "direction": "reduce repeats",
                                "added_utc": "2026-09-20T00:00:00Z"}],
        "priority_items": [
            {"rank": 1, "kind": "priority", "number": 1, "provenance": "operator", "state": "open"},
            {"rank": 2, "id": "p-3", "kind": "priority", "number": 3, "label": "Self label", "vector": "V1",
             "provenance": "self-derived", "direction": "reduce repeats", "summary": "Self label", "evidence": "x"},
        ],
        "sort": "provenance(operator<self-derived), then vector(V1<V2), as demand._priority_items",
    },
    "reflections": [{"cycle_id": "cycle-1", "summary": "private reflection", "findings": ["f"],
                     "recommendations": ["r"]}],
    "bridge_exit_streak": {"consecutive_failures": 0, "last_ts": 1_790_000_000},
    "bridge_exits": [{"ts": "2026-09-29T09:10:00Z", "cycle_id": "cycle-1", "outcome": "success", "exit_status": 0}],
    "bridge_runs": [{"run_id": "r-1", "cycle_id": "cycle-1", "phase": "run_end", "started_at": "2026-09-29T09:00:00Z",
                     "finished_at": "2026-09-29T09:10:00Z", "classification": "unit_timeout", "exit_status": "TERM"}],
    "bridge_active_run": {"run_id": "r-2", "cycle_id": "cycle-2", "started_at": "2026-09-29T10:00:00Z"},
    "strategist_decisions": [{"timestamp": "2026-09-29T08:00:00Z", "success": True, "decision": "proceeded",
                              "inputs_status": {"goals": {"status": "complete"}},
                              "counts": {"hypotheses_appended": 1, "advisories_written": 0}}],
    "demand_futility": {"gaps": {"gap:x": {"attempt_count": 8, "threshold": 10, "attempt_unit": "lever_surface",
                                           "surface": ["nanobot/runtime/x.py"], "metric": "loop.x"}}},
    "systemd_drift": {"status": "present", "state": "present", "defect_count": 1, "scanned_at": "2026-09-29T07:00:00Z",
                      "findings": {"installed_not_in_release": [{"owner": "unknown", "path": "/etc/systemd/system/x.service"}],
                                   "release_not_installed": [], "content_differs": [], "stray": []}},
    "agent_context": {
        "system_prompt": {"phase": "system_prompt", "cycle_id": "cycle-1", "ts": "2026-09-29T09:00:00Z",
                          "chars": 9000, "cap": 12000, "overflow": False, "over_by": 0, "rung": "full",
                          "sections": {"agents": 4000, "soul": 1000}, "missing": [], "truncated": [], "dropped": []},
        "truncation_streak": {"status": "no_data", "total_rows": 0, "entries": []},
        "prompt_text": "private prompt text", "task_text": "private task text",
        "tier2_skills": [{"name": "code-review", "size_bytes": 100, "desc": "private desc", "content": "private body",
                          "path": "skills/code-review/SKILL.md"}],
        "tier2_skills_status": "present",
        "tier2_lessons": {"index_status": "present", "corpus_status": "present", "corpus_count": 2,
                          "total_size_bytes": 300, "files": [{"name": "lessons.yaml", "size_bytes": 300}]},
        "tier2_memory": {"index_status": "present", "corpus_status": "present", "total_files": 1,
                         "total_size_bytes": 50, "files": [{"name": "MEMORY.md", "size_bytes": 50}]},
        "skill_reads": {"reads": [{"skill": "code-review", "confirmed": True}]},
        "skill_evals": [{"skill": "code-review", "delta": 0.1}],
        "executor_llm_stats": {"cycle_id": "cycle-1", "prompt_tokens": 5000, "ts": "2026-09-29T09:05:00Z",
                               "context_window": 32768},
        "compaction": {"status": "empty", "rows": []},
        "window_pressure": {"status": "no_data", "rows_in_window": 0, "known_rows": 0, "unknown_rows": 0},
    },
    "generator_sha": "",
    "_newest_source_age_seconds": 42.0,
    "_error": None,
    "goal_text": {"priorities": [{"title": "private operator goal"}]},
    "agents_md": "# AGENTS\nprivate agents body\n",
}


def full_source() -> dict[str, Any]:
    return copy.deepcopy(_FULL)
